import { Datagrid } from '$libs';

export const columns: Datagrid.Column[] = [
{
    prop: 'tags',
    label: 'Tags',
    columnType: 'string',
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
    width:100
  },
  {
    prop: 'contact',
    label: 'Contact',
    columnType: 'string',
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
    width: 150
  },
  {
    prop: 'src',
    label: 'Lead Source',
    columnType: 'string',
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
  },
  {
    prop: 'age',
    label: 'Lead Age',
    columnType: 'string',
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
    width: 100
  },
  {
    prop: 'name',
    label: 'Name',
    columnType: 'string',
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
  },
  
  {
    prop: 'email',
    label: 'Email',
    columnType: 'string',
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
  },
  {
    prop: 'phone',
    label: 'Phone',
    columnType: 'string',
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
    width: 100
  },
  {
    prop: 'state',
    label: 'State',
    columnType: 'string',
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
    width: 75
  },
  {
    prop: 'status',
    label: 'Lead Status',
    columnType: 'string',
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
    width: 75
  },
];
